apps/picket/admin/urls.py
"""
Copyright 2010-2011 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *

from views import *


urlpatterns = patterns('%s.views' % __package__,

    # Projects
    (r'^projects/$', ProjectsView.as_view(), {}, 'picket-admin-projects'),
    (r'^projects/new/$', ProjectView.as_view(), {},
        'picket-admin-project-new'),
    (r'^projects/(?P<project_id>\w+)/$', ProjectView.as_view(), {},
        'picket-admin-project'),
    
    # Departments
    (r'^departments/$', DepartmentsView.as_view(), {},
        'picket-admin-departments'),
    (r'^departments/new/$', DepartmentView.as_view(), {},
        'picket-admin-department-new'),
    (r'^departments/(?P<department_id>\w+)/$', DepartmentView.as_view(), {},
        'picket-admin-department'),
    
    # Stages
    (r'^stages/$', StagesView.as_view(), {},
        'picket-admin-stages'),
    (r'^stages/new/$', StageView.as_view(), {},
        'picket-admin-stage-new'),
    (r'^stages/(?P<stage_id>\w+)/$', StageView.as_view(), {},
        'picket-admin-stage'),
    
    # Employees
    (r'^employees/$', EmployeesView.as_view(), {}, 'picket-admin-employees'),
    (r'^employees/new/$', 'new_employee', {}, 'picket-admin-employee-new'),
    (r'^employees/(?P<employee_id>\w+)/$', 'employee', {},
        'picket-admin-employee'),
    (r'^employees/(?P<employee_id>\w+)/department/$', 'employee_department',
        {}, 'picket-admin-employee-department'),
)

apps/picket/urls.py
"""
Copyright 2008-2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *


urlpatterns = patterns('%s.views' % __package__,
    (r'^admin/', include('%s.admin.urls' % __package__)),
    (r'^$', 'index', {}, 'picket-index'),
    (r'^new/$', 'new_issue', {}, 'picket-issue-new'),
    (r'^(?P<issue_number>\d+)/$', 'issue', {}, 'picket-issue'),
    (r'^issues/$', 'issues', {}, 'picket-issues'),
)

picketapp/urls.py
"""
Copyright 2008 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults  import *
from django.core.urlresolvers   import reverse
from django.http                import HttpResponseRedirect

"""
TODO: project view with project summary not administration
"""
urlpatterns = patterns('picketapp.views',
    (r'^$', 'index', {},
        'picket-index',),
    (r'^filebug/$', 'filebug', {},
        'picket-filebug',),
    (r'^bugs/$', 'bugs', {},
        'picket-bugs',),
    (r'^p(?P<projectId>\d+)/$', 'project', {},
        'picket-project',),
    (r'^bugs/c(?P<categoryId>\d+)/$', 'bugs', {},
        'picket-category',),
    (r'^p(?P<projectId>\d+)/c(?P<categoryId>\d+)/b(?P<bugId>\d+)/$', 'bug', {},
        'picket-bug',),
    (r'^b(?P<bugId>\d+)/$', 'bug', {'categoryId': 0, 'projectId': 0,},
        'picket-b',),
    (r'^p\d+/c\d+/b(?P<bugId>\d+)/annotate/$', 'annotate', {},
        'picket-annotate',),
    (r'^set_p/$', 'set_project', {},
        'picket-set-project'),
    (r'^jump/$', 'jump_to_bug', {},
        'picket-jump-to-bug'),
    (r'^my/$', 'my', {},
        'picket-my-view',),
    (r'^changelog/$', 'changelog', {},
        'picket-changelog'),
    (r'^roadmap/$', 'roadmap', {},
        'picket-roadmap'),
    
    ## picket administration
    (r'^admin/', include('picketapp.admin.urls')),
)

urls.py
"""
Copyright 2008-2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.static import serve


urlpatterns = patterns('',    
    # main page:
    (r'^$', lambda req: HttpResponseRedirect(reverse('picket-index')), {},
        'index'),
    
    # picket itself
    (r'^picket/', include('apps.picket.urls')),
    
    # logout
    (r'^logout/$', logout, {'next_page': settings.LOGIN_URL}, 'auth-logout'),
)

# static
if settings.SERVE_STATIC:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    )

picketapp/models.py
"""
Copyright 2008 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.contrib.auth.models import User, Group
from django.db                  import models
from django.utils.translation   import ugettext_lazy as _

from picketapp.settings import *

class IntegrationError(Exception):
    pass

class ViewState(models.Model):
    name = models.CharField(_('view state name'),
        unique=True, max_length=255)
    groups = models.ManyToManyField(Group,
        verbose_name=_('view state groups'),
        help_text=_('groups allowed to view this view state'))
    def __unicode__(self):
        return u'%s' % self.name
    class Meta():
        verbose_name = _('view state')
        verbose_name_plural = _('view states')

class ProjectManager(models.Manager):
    def permited(self, user):
        return self.filter(view_state__groups__user = user.id)
        
class Project(models.Model):
    objects = ProjectManager()
    name = models.CharField(_('project name'),
        unique=True, max_length=255)
    status = models.PositiveIntegerField(_('project status'),
        choices=PROJECT_STATUS_CHOICES,
        default=PROJECT_STATUS_CHOICES_DEFAULT)
    enabled = models.BooleanField(_('project enabled'), default=True)
    view_state = models.ForeignKey(ViewState,
        verbose_name=_('project view state'))
    url = models.URLField(_('project url'), verify_exists=False, blank=True)
    description = models.TextField(_('project description'),
        blank=True)
    parent = models.ForeignKey('Project',
        verbose_name=_('project parent'), blank=True, null=True)
    user_list = models.ManyToManyField(User,
        verbose_name=_('project user list'), blank=True, null=True,
        related_name='project_list', through='ProjectUserList')
    
    def __unicode__(self):
        return u'%s' % self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('picket-project', [str(self.id)]) \
            if not INTEGRATION_FOREIGN_ABSOLUTE_URL \
                else self.get_integrated().get_absolute_url()
    
    def get_integrated(self):
        """
        @return: integrated project if available
        @raise IntegrationError: if integration is improperly \
configured
        TODO: make _integration_cache working as cache
        """
        if not hasattr(self, '_integration_cache'):
            if not INTEGRATION_MODEL:
                raise IntegrationError
            try:
                app_label, model_name = INTEGRATION_MODEL.split('.')
                model = models.get_model(app_label, model_name)
                self._integration_cache = model._default_manager.get(
                    project__id__exact=self.id)
            except ImportError:
                raise IntegrationError
        return self._integration_cache
    
    class Meta():
        verbose_name = _('project')
        verbose_name_plural = _('projects')

class Category(models.Model):
    project = models.ForeignKey(Project,
        verbose_name=_('category project'))
    name = models.CharField(_('category name'), max_length=192)
    handler = models.ForeignKey(User,
        verbose_name=_('category handler'), blank=True, null=True)
    def __unicode__(self):
        return u'%s: %s' % (self.project, self.name)
    @models.permalink
    def get_absolute_url(self):
        return ('picket-category', [str(self.project_id), str(self.id)])
    class Meta():
        verbose_name = _('category')
        verbose_name_plural = _('categories')
        unique_together = (('project', 'name'),)

class BugManager(models.Manager):
    def permited(self, user, project=None, category=None):
        bugs = self.filter(
            view_state__in=[viewstate.id for viewstates in [
                group.viewstate_set.all() for group in \
                user.groups.all()] for viewstate in viewstates],
            project__in=Project.objects.permited(user))
        bugs = bugs.filter(project=project) if project is not None else bugs
        bugs = bugs.filter(category=category) if category is not None else bugs
        return bugs

class Bug(models.Model):
    objects = BugManager()
    
    project = models.ForeignKey(Project, verbose_name=_('bug project'))
    reporter = models.ForeignKey(User, verbose_name=_('bug reporter'),
        related_name='reporter')
    handler = models.ForeignKey(User, verbose_name=_('bug handler'),
        related_name='handler', blank=True, null=True)
    duplicate = models.ForeignKey('self', verbose_name=_('bug duplicate'),
        related_name='duplicateOf', blank=True, null=True)
    priority = models.PositiveIntegerField(_('bug priority'),
        choices=PRIORITY_CHOICES, default=PRIORITY_CHOICES_DEFAULT)
    severity = models.PositiveIntegerField(_('bug severity'),
        choices=SEVERITY_CHOICES, default=SEVERITY_CHOICES_DEFAULT)
    reproducibility = models.PositiveIntegerField(_('bug reproducibility'),
        choices=REPRODUCIBILITY_CHOICES,
        default=REPRODUCIBILITY_CHOICES_DEFAULT)
    status = models.PositiveIntegerField(_('bug status'),
        choices=BUG_STATUS_CHOICES,
        default=BUG_STATUS_CHOICES_DEFAULT)
    resolution = models.PositiveIntegerField(_('bug resolution'),
        choices=RESOLUTION_CHOICES,
        default=RESOLUTION_CHOICES_DEFAULT)
    projection = models.PositiveIntegerField(_('bug projection'),
        choices=PROJECTION_CHOICES,
        default=PROJECTION_CHOICES_DEFAULT)
    category = models.ForeignKey(Category, verbose_name=_('bug category'))
    date_submitted = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    eta = models.PositiveIntegerField(_('bug ETA'), choices=ETA_CHOICES,
        default=ETA_CHOICES_DEFAULT)
    view_state = models.ForeignKey(ViewState, verbose_name=_('bug view state'))
    summary = models.CharField(_('bug summary'), max_length=255)
    description = models.TextField(_('bug description'))
    steps_to_reproduce = models.TextField(_('bug steps to reproduce'),
        blank=True)
    additional_information = models.TextField(_('bug additional information'),
        blank=True)
    sponsorship_total = models.IntegerField(_('bug sponsorship total'),
        default=0)
    sticky = models.BooleanField(_('bug sticky'), default=False)
    history = models.ManyToManyField(User, verbose_name=_('bug history'),
        related_name=_('history'), through='BugHistory')
    monitor = models.ManyToManyField(User, verbose_name=_('bug monitor'),
        related_name=_('monitor'), through='BugMonitor')
    relationship = models.ManyToManyField('self',
        verbose_name=_('bug relationship'), symmetrical=False,
        through='BugRelationship')
    num_bugnotes = models.PositiveIntegerField(_('bug notes count'), default=0)
    
    def __unicode__(self):
        return u'%s: %s' % (self.id, self.summary)
    
    @models.permalink
    def get_absolute_url(self):
        return ('picket-bug', [str(self.project_id), str(self.category_id),
            str(self.id)])
    
    def check_place(self, project, category):
        """
        raises exception if provided project or category are not project and
        category of the bug
        """
        if int(project) != self.project_id \
        or int(category) != self.category_id:
            raise Exception('i\'m not here')
    
    def get_status_color(self):
        return BUG_STATUS_COLORS[self.status]
    
    def get_display_columns(self):
        return [self.__getattribute__(column[0]) \
            for column in COLUMNS_BUGS_VIEW]
    
    class Meta():
        verbose_name = _('bug')
        verbose_name_plural = _('bugs')
        ordering = ['last_updated',]

class BugFile(models.Model):
    bug = models.ForeignKey(Bug, verbose_name=_('bug'))
    title = models.CharField(_('bug file title'), max_length=750)
    file = models.FileField(_('bug file'), upload_to='bugs/%Y/%m/%d-%H')
    date_added = models.DateTimeField(_('bug file date added'),
        auto_now_add=True, editable=False)
    def __unicode__(self):
        return u'%s' % self.title
    class Meta():
        verbose_name = _('bug file')
        verbose_name_plural = _('bug files')

class ProjectFile(models.Model):
    project = models.ForeignKey(Project, verbose_name=_('project'))
    title = models.CharField(_('project file title'), max_length=750)
    file = models.FileField(_('project file'),
        upload_to='projects/%Y/%m/%d-%H')
    date_added = models.DateTimeField(_('project file date added'),
        auto_now_add=True, editable=False)
    description = models.TextField(_('project file description'), blank=True)
    def __unicode__(self):
        return u'%s' % self.title
    class Meta():
        verbose_name = _('project file')
        verbose_name_plural = _('project files')

class BugHistory(models.Model):
    """
    TODO: automate me
    """
    
    user = models.ForeignKey(User,
        verbose_name=_('bug history entry user'))
    bug = models.ForeignKey(Bug, verbose_name=_('bug'))
    date_modified = models.DateTimeField(_('bug history entry date'),
        auto_now=True)
    field_name = models.CharField(_('bug history entry field'),
        max_length=96, blank=True)
    old_value = models.CharField(
        _('bug history entry old field value'),
        max_length=255, blank=True)
    new_value = models.CharField(

apps/picket/filter/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

from filter.filterset import FilterSet

def object_filter(request, model=None, queryset=None, template_name=None, extra_context=None,
    context_processors=None, filter_class=None):
    if model is None and filter_class is None:
        raise TypeError("object_filter must be called with either model or filter_class")
    if model is None:
        model = filter_class._meta.model
    if filter_class is None:
        meta = type('Meta', (object,), {'model': model})
        filter_class = type('%sFilterSet' % model._meta.object_name, (FilterSet,),
            {'Meta': meta})
    filterset = filter_class(request.GET, queryset=queryset)

    if not template_name:
        template_name = '%s/%s_filter.html' % (model._meta.app_label, model._meta.object_name.lower())
    c = RequestContext(request, {
        'filter': filterset,
    })
    if extra_context:
        for k, v in extra_context.iteritems():
            if callable(v):
                v = v()
            c[k] = v
    return render_to_response(template_name, c)

apps/picket/templates/picket/base.html
{% extends 'base.html' %}{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block messages %}
{% if messages %}{% for message in messages %}
<div class="ui-state-highlight">{{ message }}</div>
{% endfor %}{% endif %}
{% endblock %}

{% block content %}

{% include 'picket/header.html' %}

<div id="picket-content" class="picket-content">
{% if not projects %}
<div class="ui-state-error">{% trans 'There is no project exists!' %}<br />
<a href="{% url picket-admin-project-new %}">{% trans 'Configure at least one project.' %}</a></div>
{% endif %}
{% block picket %}
{% endblock picket %}
</div>
<div class="endline">&nbsp;</div>

{% include 'picket/footer.html' %}

{% endblock content %}

apps/picket/templates/picket/bug.html
{% extends 'picket/base.html' %}{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}


{% block picket %}

{{ bug }}

{% endblock picket %}

apps/picket/templates/picket/footer.html
{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

<div id="picket-footer">
    <p class="copyright">Picket {{ copying.VERSION }}<br />
    &copy; {{ copying.YEARS|first }}&mdash;{{ copying.YEARS|last }} {{ copying.AUTHORS|join:', ' }}</p>
</div>

apps/picket/templates/picket/header.html
{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

<div class="header">
  <div class="header-left">
    <div>
      <h1 class="picket-title">Picket</h1>
      <div class="picket-search">
        <form class="search-form">
	        <input class="search" type="text" name="search" value="{% trans 'Search issues' %}" onfocus="this.value='';" /><br />
	        <label><input type="radio" name="search_area" value="current" />{% trans 'Current project' %}</label>
	        <label><input type="radio" name="search_area" value="all" />{% trans 'All projects' %}</label>
	        <input type="submit" />
        </form>
      </div>
      <div class="clear">&nbsp;</div>
    </div>
    <div>
      <div class="picket-menu">{% include 'picket/inc/menu.html' %}</div>
      <div class="current-project">{% include 'picket/inc/project_selector.html' %}</div>
      <div class="clear">&nbsp;</div>
    </div>
  </div>
  <div class="header-right">
    <div class="userbox">{% include 'picket/inc/userbox.html' %}</div>
  </div>
  <div class="clear">&nbsp;</div>
</div>
<div class="endline">&nbsp;</div>

apps/picket/templates/picket/index.html
{% extends 'picket/base.html' %}{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}


{% block picket %}



{% endblock picket %}

apps/picket/templates/picket/issue.html
{% extends 'picket/base.html' %}{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}


{% block picket %}

{{ issue }}

{% endblock picket %}

apps/picket/templates/picket/issues.html
{% extends 'picket/base.html' %}{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}


{% block picket %}

<p>{% for issue in issues %}
<a href="{% url picket-issue issue.id %}">{{ issue }}</a><br />
{% endfor %}</p>

{% endblock picket %}

apps/picket/templates/picket/menu_inc.html
{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

<ul>
    <li><a href="{% url picket-issue-new %}">{% trans 'New issue' %}</a></li> |
    <li><a href="{% url picket-index %}">{% trans 'Home' %}</a></li> |
    <li><a href="% url picket-workspace %">{% trans 'Workspace' %}</a></li> |
    <li><a href="{% url picket-issues %}">{% trans 'Issue list' %}</a></li> |
    <li><a href="% url picket-help %">{% trans 'Help' %}</a></li>
</ul>

{% if my_departments %}
<ul>
    <li>{% trans 'Departments' %}:</li>
    {% for department in my_departments %}
    <li><a href="{{ department.get_absolute_url }}">{{ department }}</a></li>
    {% endfor %}
</ul>
{% endif %}

{% if my_projects %}
<ul>
    <li>{% trans 'Projects' %}:</li>
    {% for project in my_projects %}
    <li><a href="{{ project.get_absolute_url }}">{{ project }}</a></li>
    {% endfor %}
</ul>
{% endif %}

apps/picket/templates/picket/new_bug.html
{% extends 'picket/base.html' %}{% load i18n %}
{% comment %}
Copyright 2010 Serge Matveenko

This file is part of Picket.

Picket is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Picket is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Picket.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}


{% block picket %}

<form action="" method="post" class="new_bug_form">

{{ new_bug_form.severity }}
<script type="text/javascript">
$(function() {
    $('#id_severity').selectToUISlider({
        labels: {{ new_bug_form.fields.severity.widget.choices|length }},
        tooltip: false,
        labelSrc: 'text',
        sliderOptions: {
            animate: true,
        }
    }).hide();
});
</script>

{% if not user.is_authenticated %}
<p>{{ new_bug_form.reporter_email.label_tag }}<br />
{{ new_bug_form.reporter_email }}</p>
{% endif %}

<p>{{ new_bug_form.summary.label_tag }}<br />
{{ new_bug_form.summary }}</p>

<p>{{ new_bug_form.description.label_tag }}<br />
{{ new_bug_form.description }}</p>

<p><span class="inline_inputs"><input type="submit" class="submit" /> {% if user.is_authenticated %}{{ new_bug_form.return_to_form }} {{ new_bug_form.return_to_form.label_tag }}{% endif %}</span></p>

</form>

{% endblock picket %}